### PR TITLE
Merge upstream changes.

### PR DESCRIPTION
**Pull request by orbea**
This updates this shallow fork again with upstream changes.

Most of these changes are not relevant for libretro, but this crash fix with no content would be nice to have.

https://github.com/AZO234/NP2kai/pull/57

I would also suggest that it might be fine to just use the upstream repo, but that is a discussion for another time.

### CODE REVIEW

**Comment by inactive123** [comment]
A shallow fork still has its uses, when we need to push updates for platforms that get broken inbetween commits. This has happened a couple of times already and when this happens, the entire WiiU port no longer compiles, so it needs to be fixed as soon as possible in most cases, hence why a shallow fork is still the only viable solution there.

However, I have zero issue with adhering close to upstream otherwise.  If you want to be a middleman pushing those updates to upstream then, alright with me.

**Comment by orbea** [comment]
Whatever works for you is fine with me. I just want to see these silly crashes finally fixed and updating the core for the buildbot is a required step here. :)

Also it got me to notice that is this a pretty cool core.

**Comment by inactive123** [comment]
I'll merge it for now. Hopefully the platforms that have been building up until now will keep building.

**Comment by orbea** [comment]
Please ping me if it doesn't and I will attempt to help investigate and coordinate with upstream to solve issues.

**Comment by inactive123** [comment]
It fails building now for 32bit Windows -

http://p.0bl.net/35781

Honestly, it would solve a whole lot if instead of having to build the SDL2 frontend code, we would have our own libretro code where we go through 'sane' wrappers like the stuff we have in libretro-common instead of this stuff that keeps falling apart every single time. That SDL2 frontend code is not portable enough for us, we need our own code that doesn't continually break time and time again.

**Comment by orbea** [comment]
@twinaphex Here is a potential fix.

https://github.com/libretro/NP2kai/pull/3

I agree about using libretro-common instead, but getting the ball rolling again is more important first.

**Comment by inactive123** [comment]
OK.

**Pull request merged**
